# This workflows will upload a Python Package using Twine when a release is created
# Also a package for node is created and uploaded
# author: Omar.Zapata@cern.ch 2020

name: SWAN CI/CD pipeline

on:
  push:
    tags:
       - '*/v*'
  
jobs:
  build-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '12.x'

    - name: Set environnment package name  and version
      run: |
        echo ::set-env name=PACKAGE_TAG::${GITHUB_REF#refs/*/}
        echo ::set-env name=PACKAGE_NAME::$(echo  ${GITHUB_REF#refs/*/} | cut -d / -f 1)

    - name: Install dependencies 
      run: |
        cd $PACKAGE_NAME
        pip3 install setuptools wheel 
        pip3 install jupyter_packaging jupyterlab

    - name: Build wheel
      run: |
        cd $PACKAGE_NAME
        python3 setup.py sdist bdist_wheel

    - name: Publish distribution to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        cd $PACKAGE_NAME
        twine upload --repository testpypi dist/*

    - name: Publish distribution to NPM
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cd $PACKAGE_NAME
        npm publish  -dry-run
